# Generated by Django 6.0.6 on 2026-06-29 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(choices=[('🌅', 'Sunrise'), ('🚿', 'Shower'), ('🚫', 'No'), ('📖', 'Reading'), ('🍷', 'No Alcohol'), ('💪', 'Workout'), ('🌙', 'Bedtime'), ('🧘', 'Meditation'), ('📝', 'Journal'), ('💧', 'Water'), ('🏃', 'Running'), ('🎯', 'Focus'), ('🧠', 'Learning'), ('💤', 'Sleep'), ('🥗', 'Healthy Eating'), ('📱', 'No Phone'), ('🎵', 'Music'), ('✍️', 'Writing'), ('🎨', 'Creative'), ('🏋️', 'Strength'), ('🧹', 'Clean'), ('🌳', 'Nature'), ('🙏', 'Gratitude'), ('💡', 'Idea'), ('⭐', 'Star'), ('🔥', 'Streak'), ('✅', 'Complete'), ('📊', 'Progress')], default='✅', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
