# Generated by Django 6.0.6 on 2026-06-25 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('TASKS', 'Task Master'), ('STREAK', 'Streak Warrior'), ('LEVEL', 'Level Up'), ('SPECIAL', 'Special')], default='TASKS', max_length=20)),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('requirement_type', models.CharField(choices=[('TASKS_COMPLETED', 'Number of tasks completed'), ('STREAK_DAYS', 'Consecutive days with activity'), ('LEVEL_REACHED', 'Reach a specific level'), ('XP_EARNED', 'Total XP earned')], max_length=20)),
                ('requirement_value', models.IntegerField()),
                ('xp_reward', models.IntegerField(default=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Achievements',
                'ordering': ['order', 'requirement_value'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
