# Generated by Django 6.0.6 on 2026-06-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('TASKS', 'Task Master'), ('STREAK', 'Streak Warrior'), ('HABITS', 'Habit Builder'), ('LEVEL', 'Level Up'), ('SPECIAL', 'Special')], default='TASKS', max_length=20),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='requirement_type',
            field=models.CharField(choices=[('TASKS_COMPLETED', 'Number of tasks completed'), ('STREAK_DAYS', 'Consecutive days with activity'), ('LEVEL_REACHED', 'Reach a specific level'), ('XP_EARNED', 'Total XP earned'), ('HABITS_CREATED', 'Number of habits created'), ('HABITS_COMPLETED', 'Number of habits completed in a month')], max_length=20),
        ),
    ]
